local ui = {}

local c = require("nord.colors")

function ui.highlights()
  return {
    -- WhichKey
    WhichKey = { fg = c.frost.ice, bold = true },
    WhichKeyGroup = { fg = c.frost.artic_water },
    WhichKeyDesc = { fg = c.snow_storm.origin },
    WhichKeyFloat = { bg = c.polar_night.bright },

    -- Navic
    NavicIconsFile = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsModule = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsNamespace = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsPackage = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsClass = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsMethod = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsProperty = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsField = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsConstructor = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsEnum = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsInterface = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsFunction = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsVariable = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsConstant = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsString = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsNumber = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsBoolean = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsArray = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsObject = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsKey = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsKeyword = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsNull = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsEnumMember = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsStruct = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsEvent = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsOperator = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicIconsTypeParameter = { fg = c.frost.polar_water, bg = c.polar_night.brightest },
    NavicText = { fg = c.snow_storm.origin, bg = c.polar_night.brightest },
    NavicSeparator = { fg = c.frost.artic_water, bg = c.polar_night.brightest },

    AerialLine = { bg = c.polar_night.bright },
    AerialLineNC = { bg = c.polar_night.bright },

    AerialArrayIcon = { fg = c.aurora.yellow },
    AerialBooleanIcon = { fg = c.frost.artic_water, bold = true },
    AerialClassIcon = { fg = c.frost.artic_water },
    AerialConstantIcon = { fg = c.aurora.yellow },
    AerialConstructorIcon = { fg = c.frost.artic_water },
    AerialEnumIcon = { fg = c.frost.artic_water },
    AerialEnumMemberIcon = { fg = c.snow_storm.origin },
    AerialEventIcon = { fg = c.frost.artic_water },
    AerialFieldIcon = { fg = c.snow_storm.origin },
    AerialFileIcon = { fg = c.aurora.green },
    AerialFunctionIcon = { fg = c.frost.ice },
    AerialInterfaceIcon = { fg = c.frost.artic_water },
    AerialKeyIcon = { fg = c.frost.artic_water },
    AerialMethodIcon = { fg = c.frost.polar_water },
    AerialModuleIcon = { fg = c.snow_storm.origin },
    AerialNamespaceIcon = { fg = c.snow_storm.origin },
    AerialNullIcon = { fg = c.frost.artic_water },
    AerialNumberIcon = { fg = c.aurora.purple },
    AerialObjectIcon = { fg = c.frost.artic_water },
    AerialOperatorIcon = { fg = c.frost.artic_water },
    AerialPackageIcon = { fg = c.snow_storm.origin },
    AerialPropertyIcon = { fg = c.frost.artic_ocean },
    AerialStringIcon = { fg = c.aurora.green },
    AerialStructIcon = { fg = c.frost.artic_water },
    AerialTypeParameterIcon = { fg = c.frost.artic_ocean },
    AerialVariableIcon = { fg = c.snow_storm.origin, bold = true },

    AerialArray = { fg = c.aurora.yellow },
    AerialBoolean = { fg = c.frost.artic_water, bold = true },
    AerialClass = { fg = c.frost.artic_water },
    AerialConstant = { fg = c.aurora.yellow },
    AerialConstructor = { fg = c.frost.artic_water },
    AerialEnum = { fg = c.frost.artic_water },
    AerialEnumMember = { fg = c.snow_storm.origin },
    AerialEvent = { fg = c.frost.artic_water },
    AerialField = { fg = c.snow_storm.origin },
    AerialFile = { fg = c.aurora.green },
    AerialFunction = { fg = c.frost.ice },
    AerialInterface = { fg = c.frost.artic_water },
    AerialKey = { fg = c.frost.artic_water },
    AerialMethod = { fg = c.frost.polar_water },
    AerialModule = { fg = c.snow_storm.origin },
    AerialNamespace = { fg = c.snow_storm.origin },
    AerialNull = { fg = c.frost.artic_water },
    AerialNumber = { fg = c.aurora.purple },
    AerialObject = { fg = c.frost.artic_water },
    AerialOperator = { fg = c.frost.artic_water },
    AerialPackage = { fg = c.snow_storm.origin },
    AerialProperty = { fg = c.frost.artic_ocean },
    AerialString = { fg = c.aurora.green },
    AerialStruct = { fg = c.frost.artic_water },
    AerialTypeParameter = { fg = c.frost.artic_ocean },
    AerialVariable = { fg = c.snow_storm.origin, bold = true },
  }
end

return ui
